# Generated by Django 6.0.7 on 2026-07-31 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(default='General', max_length=50)),
                ('location_name', models.CharField(default='Unknown Location', max_length=255)),
                ('district_id', models.CharField(default='unknown', max_length=100)),
                ('lat', models.FloatField(default=27.7)),
                ('lng', models.FloatField(default=85.3)),
                ('first_reported', models.DateTimeField()),
                ('last_reported', models.DateTimeField()),
                ('severity', models.IntegerField(default=3)),
                ('is_life_threat', models.BooleanField(default=False)),
                ('vulnerability', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('manual_priority', models.IntegerField(blank=True, null=True)),
                ('manually_adjusted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['first_reported'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_wt', models.IntegerField(default=3)),
                ('corroboration_wt', models.IntegerField(default=2)),
                ('trust_wt', models.IntegerField(default=2)),
                ('vulnerability_wt', models.IntegerField(default=1)),
                ('time_wt', models.IntegerField(default=1)),
                ('distance_threshold_km', models.FloatField(default=15.0)),
                ('time_threshold_hours', models.FloatField(default=24.0)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.incident')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('call_center', 'Call Center'), ('sensor', 'Sensor Alert'), ('social_media', 'Social Media')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('description', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.IntegerField(default=3)),
                ('is_life_threat', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(default=dict)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='core.incident')),
            ],
        ),
    ]
