# Generated by Django 6.0.7 on 2026-07-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='disaster_type',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
